name: Python and JS Quality Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # --- PARTE PYTHON (CONDA) ---
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.10"
        activate-environment: estimador-env
        environment-file: environment.yml

    - name: Lint Python
      shell: bash -l {0}
      run: |
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # --- PARTE JAVASCRIPT (ESLint) ---
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install and Run ESLint
      run: |
        npm install eslint
        npx eslint js/calculadora.js